In [23]:
import pandas as pd
pd.options.mode.chained_assignment = None 
import numpy as np
import re
import nltk
import pickle
from gensim.models import word2vec
from gensim.models import KeyedVectors
from sklearn.manifold import TSNE
import matplotlib.pyplot as plt
import bisect

In [3]:
%matplotlib

Using matplotlib backend: MacOSX


In [ ]:
# model = KeyedVectors.load('w2v-models/economic-word2vec')
model = KeyedVectors.load('/Users/navreetkaur/MTP/finetune-word2vec/w2v-models/prev/aadhar_w2v')

In [21]:
model.most_similar(positive=['Modi'])

[('Pawar', 0.7882996201515198),
 ('Advani', 0.770244836807251),
 ('Jaitley', 0.740410327911377),
 ('Deshmukh', 0.7383387088775635),
 ('Gadkari', 0.7377650737762451),
 ('BJP', 0.7223128080368042),
 ('Chavan', 0.7213584184646606),
 ('Gujarat', 0.7121881246566772),
 ('Rahul', 0.7093901038169861),
 ('Gehlot', 0.7076128721237183)]

In [57]:
model.most_similar(positive=['Gandhi'])

[('Gandhiji', 0.8086377382278442),
 ('Mahatma', 0.7583321928977966),
 ('Bapu', 0.7056624889373779),
 ('Gandhian', 0.6756616830825806),
 ('Ambedkar', 0.6688408851623535),
 ('Advani', 0.6528218388557434),
 ('Mayawati', 0.6415842175483704),
 ('Gandhis', 0.6389546394348145),
 ('Modi', 0.6382002234458923),
 ('Tagore', 0.6329137086868286)]

In [149]:
bjp = ['Advani',
'Jaitley',
'Gadkari',
'Javdekar',
'Modi',
'Javadekar',
'Bidhuri',
'Jethmalani',
'Swaraj',
'Rajnath',
'Fadnavis',
'Tiwari',
'Thackeray',
'Gadkari',
'Vajpayee',
'Sitharaman',
'Rijiju',
'Irani',
'Shah']
len(set(bjp))

18

In [155]:
inc = ['Mukherjee',
'Chidamabaram',
'Pawar',
'Nirupam',
'Deshmukh',
'Chavan',
'Gehlot',
'Yechury',
'Moily',
'Pranab',
'Bhattacharjee',
'Rosaiah', 
'Natwar',
'Rahul', 
'Montek', 
'Chidambaram', 
'Nitish', 
'Mukherjee', 
'Mayawati',
'Bhattacharjee',
'Mamata',
'Naidu',
'Kejriwal',
'Amarinder',
'Gehlot',
'Azad',
'Gogoi',
'Khurshid',
'Chavan',
'Chandy',
'Deshmukh',
'Togadia']
len(set(inc))

27

In [5]:
labels = []
tokens = []

for word in model.wv.vocab:
    tokens.append(model[word])
    labels.append(word)

/Users/navreetkaur/Library/Python/3.7/lib/python/site-packages/ipykernel_launcher.py:5: DeprecationWarning: Call to deprecated `wv` (Attribute will be removed in 4.0.0, use self instead).
  """


In [9]:
# tsne_model = TSNE(perplexity=20, n_components=2, n_iter=250)
tsne_model = TSNE(n_components=2)
new_values = tsne_model.fit_transform(tokens)
# pickle.dump(new_values, open('tsne_values_economic.pkl', 'wb'))

In [6]:
new_values = pickle.load(open('tsne_values_economic.pkl', 'rb'))

In [44]:
new_values[6742], new_values[3983], new_values[8814]

(array([21.321741, 29.58546 ], dtype=float32),
 array([18.508123, -5.350962], dtype=float32),
 array([27.993734 , -2.7425878], dtype=float32))

In [53]:
i = L.index('Jaitley')
X[i], Y[i]

(21.233767, 29.705662)

In [9]:
x = []
y = []
for value in new_values:
    x.append(value[0])
    y.append(value[1])

In [16]:
new_vals = [(i,j,k) for i,j,k in sorted(zip(x,y,labels))]
X, Y, L = list(zip(*new_vals))
# len(X), len(Y), len(L)

In [56]:
X[L.index('Gandhi')], Y[L.index('Gandhi')], X[L.index('Modi')], Y[L.index('Modi')]

(18.82821, 23.45381, 21.321741, 29.58546)

In [54]:
bisect.bisect_left(X, 18.5), bisect.bisect_left(X, 22)

(71853, 77893)

In [49]:
X[72378], Y[72378]

(18.82821, 23.45381)

In [55]:
fig = plt.figure(figsize=(10, 10)) 
for i in range(71853, 77893):
    if (Y[i]>20):
        plt.scatter(X[i],Y[i],c='blue')
        plt.annotate(L[i],
                     xy=(X[i], Y[i]))
        #                  xytext=(5, 2),
        #                  textcoords='offset points',
        #                  ha='right',
        #                  va='bottom'
plt.show()

In [157]:
bjp = set(bjp)
inc = set(inc)
bjp, inc, len(bjp), len(inc)

({'Advani',
  'Bidhuri',
  'Fadnavis',
  'Gadkari',
  'Irani',
  'Jaitley',
  'Javadekar',
  'Javdekar',
  'Jethmalani',
  'Modi',
  'Rajnath',
  'Rijiju',
  'Shah',
  'Sitharaman',
  'Swaraj',
  'Thackeray',
  'Tiwari',
  'Vajpayee'},
 {'Amarinder',
  'Azad',
  'Bhattacharjee',
  'Chandy',
  'Chavan',
  'Chidamabaram',
  'Chidambaram',
  'Deshmukh',
  'Gehlot',
  'Gogoi',
  'Kejriwal',
  'Khurshid',
  'Mamata',
  'Mayawati',
  'Moily',
  'Montek',
  'Mukherjee',
  'Naidu',
  'Natwar',
  'Nirupam',
  'Nitish',
  'Pawar',
  'Pranab',
  'Rahul',
  'Rosaiah',
  'Togadia',
  'Yechury'},
 18,
 27)

In [175]:
model.most_similar('Pranab')

[('Manmohan', 0.7674049139022827),
 ('Montek', 0.7490100264549255),
 ('Chidambaram', 0.7217987775802612),
 ('Mukherjee', 0.7174678444862366),
 ('Rajnath', 0.6912670135498047),
 ('Venkaiah', 0.665076494216919),
 ("K'taka", 0.6622086763381958),
 ('Mamata', 0.6590150594711304),
 ('Jaswant', 0.6549724340438843),
 ('Advani', 0.6474892497062683)]

In [212]:
bjp = ['Mungantiwar', 'Tawde', 'Raote', 'Velankar', 'Ananthkumar', 
       'Advani',
  'Bidhuri',
  'Fadnavis',
  'Jaitley',
#   'Javadekar',
  'Javdekar',
#   'Jethmalani',
  'Modi',
  'Rijiju',
#   'Sitharaman',
  'Swaraj',
  'Thackeray',
#   'Vajpayee' 
      ]
len(set(bjp))

14

In [213]:
inc = ['Bhattacharjee', 'Sinha',  'Ahluwalia', 'Bhattacharjee', 'Banerjee', 'Manmohan', 
  'Chidambaram',
  'Gogoi',
  'Kejriwal',
  'Khurshid',
  'Mayawati',
  'Montek',
  'Mukherjee',
  'Natwar',
  'Nitish',
  'Pranab',
  'Rosaiah',
  'Yechury']
len(set(inc))

17

In [214]:
fig = plt.figure(figsize=(10, 10)) 

In [215]:
for name in set(bjp):
    i = L.index(name)
    plt.scatter(X[i],Y[i],c='blue')
    plt.annotate(L[i],
                 xy=(X[i], Y[i]))

for name in set(inc):
    i = L.index(name)
    plt.scatter(X[i],Y[i],c='red')
    plt.annotate(L[i],
                 xy=(X[i], Y[i]))

plt.show()