In [5]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer

In [6]:
corpus = [
    'This is the first document.',
    'This document is the second document.',
    'And this is the third one.',
    'Is this the first document?',
]
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(corpus)
print(X.shape)

(4, 9)


In [7]:
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)
print(vectorizer.get_feature_names())

print(X.toarray())

['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third', 'this']
[[0 1 1 1 0 0 1 0 1]
 [0 2 0 1 0 1 1 0 1]
 [1 0 0 1 1 0 1 1 1]
 [0 1 1 1 0 0 1 0 1]]


In [8]:
from bert_serving.client import BertClient
bc = BertClient()
bc.encode(['First do it', 'then do it right', 'then do it better'])

KeyboardInterrupt: 

In [ ]:
from sklearn.manifold import TSNE
from ggplot import *
import pandas as pd
import numpy as np

def tsne_projection(tsne_matrix, train_y, info):
    tsne = TSNE(n_components=2, verbose=1, perplexity=40, n_iter=5000)
    tsne_results = tsne.fit_transform(tsne_matrix)

    df_tsne = pd.DataFrame(data=np.float_(tsne_matrix), index=[str(i) for i in range(tsne_matrix.shape[0])])
    df_tsne['x-tsne'] = tsne_results[:,0]
    df_tsne['y-tsne'] = tsne_results[:,1]
    df_tsne['label'] = train_y
    df_tsne['label'] = df_tsne['label'].apply(lambda i: str(int(i)))
    chart = ggplot( df_tsne, aes(x='x-tsne', y='y-tsne', color='label') ) \
            + geom_point(size=60,alpha=0.6) \
            + ggtitle("{info} : tSNE dimensions colored by subject".format(info=info))
    return chart